#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# Configs

xrandr --output HDMI1 --primary &
xrandr -s 1920x1080
xrandr --output HDMI1 --auto --rotate normal --pos 0x0 --output eDP1 --auto --rotate normal --left-of HDMI1
bspc monitor HDMI1 -d I II III IV V VI
 
#bspc monitor -d I II III IV 

bspc config top_padding 50
bspc config left_padding 20
bspc config right_padding 20
bspc config bottom_padding 20

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "$BACKGROUND"
bspc config focused_border_color "$BACKGROUND"
bspc config presel_feedback_color "$BACKGROUND"

bspc config split_ratio          0.50
bspc config gapless_monocle      true

# AutoStart

feh --bg-fill --fullscreen $HOME/CurrentWallpaper/wallpaper.png &
picom &
$HOME/.config/polybar/launch.sh &
dunst &
