#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-1 --primary &

bspc monitor HDMI-1 -d I II III IV V

bspc config top_padding 50
bspc config left_padding 20
bspc config right_padding 20
bspc config bottom_padding 20

bspc config split_ratio          0.52
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^4'
bspc rule -a discord-canary desktop='^5'

setxkbmap -model abnt2 -layout pt &
hsetroot -cover ./CurrentWallpaper/wallpaper.png &
picom &
$HOME/.config/polybar/launch.sh &
dunst &
